// Seed data for demo — realistic Indian IT staffing candidates
import { processCandidate, type CandidateIntake } from "./scoring"
import {
  getDb,
  upsertCandidate,
  upsertReviewQueue,
  appendStageUpdate,
  createReviewFromCandidate,
  createIntakeStageUpdate,
} from "./store"

const DEMO_CANDIDATES: CandidateIntake[] = [
  {
    candidate_name: "Aditya Kumar",
    phone: "+919876543210",
    email: "aditya.k@gmail.com",
    recruiter_id: "rec_001",
    recruiter_name: "Ananya Desai",
    role: "Senior Java Developer",
    skill_stack: "Java, Spring Boot, Microservices, AWS, Kafka",
    total_experience: "8 years",
    current_location: "Hyderabad",
    current_compensation: 1800000,
    expected_compensation: 3200000,
    notice_period_days: 90,
    buyout_possible: "no",
    earliest_joining_date: new Date(Date.now() + 90 * 86400000).toISOString(),
    job_location: "Bangalore",
    work_mode: "hybrid",
    relocation_willingness: "maybe",
    resume_received: "yes",
    available_for_interview_soon: "maybe",
    last_response_timestamp: new Date(Date.now() - 96 * 3600000).toISOString(),
    notes: "Strong profile but high hike expectation and silent for 4 days",
    current_stage: "Screening",
  },
  {
    candidate_name: "Priya Sharma",
    phone: "+919876543211",
    email: "priya.sharma@outlook.com",
    recruiter_id: "rec_001",
    recruiter_name: "Ananya Desai",
    role: "React Frontend Lead",
    skill_stack: "React, TypeScript, Next.js, Tailwind, Node.js",
    total_experience: "6 years",
    current_location: "Pune",
    current_compensation: 1500000,
    expected_compensation: 2000000,
    notice_period_days: 30,
    buyout_possible: "yes",
    earliest_joining_date: new Date(Date.now() + 30 * 86400000).toISOString(),
    job_location: "Pune",
    work_mode: "hybrid",
    relocation_willingness: "no",
    resume_received: "yes",
    available_for_interview_soon: "yes",
    last_response_timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    notes: "Responsive, reasonable expectations",
    current_stage: "Interview Scheduled",
  },
  {
    candidate_name: "Rahul Verma",
    phone: "+919876543212",
    email: "rahul.v@gmail.com",
    recruiter_id: "rec_002",
    recruiter_name: "Vikram Singh",
    role: "DevOps Engineer",
    skill_stack: "AWS, Terraform, Docker, Kubernetes, Jenkins, Python",
    total_experience: "5 years",
    current_location: "Noida",
    current_compensation: 1200000,
    expected_compensation: 2500000,
    notice_period_days: 60,
    buyout_possible: "unknown",
    earliest_joining_date: new Date(Date.now() + 60 * 86400000).toISOString(),
    job_location: "Gurgaon",
    work_mode: "office",
    relocation_willingness: "maybe",
    resume_received: "yes",
    available_for_interview_soon: "yes",
    last_response_timestamp: new Date(Date.now() - 30 * 3600000).toISOString(),
    notes: "High hike ask, relocation uncertain",
    current_stage: "Interview Done",
  },
  {
    candidate_name: "Sneha Patel",
    phone: "+919876543213",
    email: "sneha.p@yahoo.com",
    recruiter_id: "rec_001",
    recruiter_name: "Ananya Desai",
    role: "QA Automation Lead",
    skill_stack: "Selenium, Java, Cypress, API Testing, JIRA",
    total_experience: "7 years",
    current_location: "Mumbai",
    current_compensation: 1400000,
    expected_compensation: 1700000,
    notice_period_days: 30,
    buyout_possible: "yes",
    earliest_joining_date: new Date(Date.now() + 15 * 86400000).toISOString(),
    job_location: "Mumbai",
    work_mode: "hybrid",
    relocation_willingness: "no",
    resume_received: "yes",
    available_for_interview_soon: "yes",
    last_response_timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    notes: "Excellent candidate, low risk",
    current_stage: "Offer Extended",
  },
  {
    candidate_name: "Karthik Nair",
    phone: "+919876543214",
    email: "karthik.n@gmail.com",
    recruiter_id: "rec_002",
    recruiter_name: "Vikram Singh",
    role: "Python Data Engineer",
    skill_stack: "Python, PySpark, Airflow, SQL, Snowflake, dbt",
    total_experience: "4 years",
    current_location: "Chennai",
    current_compensation: 1000000,
    expected_compensation: 1800000,
    notice_period_days: 60,
    buyout_possible: "no",
    earliest_joining_date: new Date(Date.now() + 60 * 86400000).toISOString(),
    job_location: "Bangalore",
    work_mode: "office",
    relocation_willingness: "no",
    resume_received: "no",
    available_for_interview_soon: "no",
    last_response_timestamp: new Date(Date.now() - 78 * 3600000).toISOString(),
    notes: "Not willing to relocate, doesn't want office mode. Silent 3 days.",
    current_stage: "Screening",
  },
  {
    candidate_name: "Meera Iyer",
    phone: "+919876543215",
    email: "meera.iyer@gmail.com",
    recruiter_id: "rec_001",
    recruiter_name: "Ananya Desai",
    role: "Full Stack Developer",
    skill_stack: "Node.js, React, PostgreSQL, Docker, GraphQL",
    total_experience: "3 years",
    current_location: "Bangalore",
    current_compensation: 900000,
    expected_compensation: 1200000,
    notice_period_days: 30,
    buyout_possible: "yes",
    earliest_joining_date: new Date(Date.now() + 20 * 86400000).toISOString(),
    job_location: "Bangalore",
    work_mode: "hybrid",
    relocation_willingness: "yes",
    resume_received: "yes",
    available_for_interview_soon: "yes",
    last_response_timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
    notes: "Quick responder, reasonable expectations",
    current_stage: "Offer Accepted",
  },
  {
    candidate_name: "Arjun Mehta",
    phone: "+919876543216",
    email: "arjun.m@gmail.com",
    recruiter_id: "rec_002",
    recruiter_name: "Vikram Singh",
    role: "Cloud Architect",
    skill_stack: "AWS, Azure, Terraform, Python, Serverless",
    total_experience: "10 years",
    current_location: "Delhi",
    current_compensation: 2500000,
    expected_compensation: 5000000,
    notice_period_days: 90,
    buyout_possible: "unknown",
    earliest_joining_date: new Date(Date.now() + 90 * 86400000).toISOString(),
    job_location: "Remote",
    work_mode: "remote",
    relocation_willingness: "no",
    resume_received: "yes",
    available_for_interview_soon: "maybe",
    last_response_timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
    notes: "100% hike ask. Very senior but extremely risky.",
    current_stage: "Intake",
  },
  {
    candidate_name: "Divya Reddy",
    phone: "+919876543217",
    email: "divya.r@gmail.com",
    recruiter_id: "rec_001",
    recruiter_name: "Ananya Desai",
    role: "UI/UX Designer",
    skill_stack: "Figma, Sketch, Design Systems, Prototyping, User Research",
    total_experience: "5 years",
    current_location: "Hyderabad",
    current_compensation: 1100000,
    expected_compensation: 1400000,
    notice_period_days: 30,
    buyout_possible: "yes",
    earliest_joining_date: new Date(Date.now() + 25 * 86400000).toISOString(),
    job_location: "Hyderabad",
    work_mode: "hybrid",
    relocation_willingness: "no",
    resume_received: "yes",
    available_for_interview_soon: "yes",
    last_response_timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    notes: "Good fit, ready to interview",
    current_stage: "Interview Scheduled",
  },
]

export async function seedDemoData() {
  // Clear all collections before seeding to prevent duplicates
  const db = await getDb()
  await Promise.all([
    db.collection("candidate_master").deleteMany({}),
    db.collection("review_queue").deleteMany({}),
    db.collection("stage_updates").deleteMany({}),
    db.collection("messages").deleteMany({}),
    db.collection("behavioral_profiles").deleteMany({}),
  ])

  let seeded = 0
  for (const intake of DEMO_CANDIDATES) {
    const scored = processCandidate(intake)
    await upsertCandidate(scored)
    await appendStageUpdate(createIntakeStageUpdate(scored))
    if (scored.review_required) {
      await upsertReviewQueue(createReviewFromCandidate(scored))
    }
    seeded++
  }
  return { seeded }
}
